/** 管理端：域菜单模块 → 专用页面（非通用 ModuleCrud） */
export const ADMIN_SPECIAL_MODULE_PATHS: Record<string, string> = {
  '销售管理/销售订单': '/sales/hub/orders',
  '销售管理/修改订单': '/sales/hub/order-edit',
  '销售管理/订单复购': '/sales/hub/order-rebuy',
  '销售管理/我的订单': '/sales/hub/my-orders',
  '销售管理/询价管理': '/sales/hub/inquiries',
  '销售管理/询价审批': '/sales/hub/inquiry-approve',
  '销售管理/预发货管理': '/sales/hub/pre-ships',
  '销售管理/发货审批': '/sales/hub/deliveries',
  '销售管理/销售锁价': '/sales/hub/price-locks',
  '销售管理/合同管理': '/sales/hub/contracts',
  '销售管理/历史报价查询': '/sales/hub/quotes',
  '销售管理/数据排行榜': '/sales/hub/rankings',
  '销售管理/销售BOM': '/sales/hub/boms',
  '销售管理/成本预算': '/sales/hub/budgets',
  '销售管理/报价计算器': '/sales/hub/calculator',
  '销售管理/单据打印': '/sales/hub/prints',
  '销售管理/自助下单': '/sales/hub/self-orders',
  '销售管理/出厂结算': '/sales/outbound-settle',
  '客户管理/CRM客户管理': '/crm/hub/customers',
  '客户管理/商机管理': '/crm/hub/opportunities',
  '客户管理/客户档案': '/crm/hub/profile',
  '客户管理/客户跟进': '/crm/hub/follow-ups',
  '客户管理/资源分配': '/crm/hub/assigns',
  '客户管理/保护机制': '/crm/hub/protect',
  '客户管理/释放机制': '/crm/hub/releases',
  '客户管理/询价管理': '/crm/hub/inquiries',
  '客户管理/导入客户': '/crm/hub/imports',
  '客户管理/线索锁定': '/crm/hub/locks',
  '客户管理/线索隐藏': '/crm/hub/hides',
  '客户管理/任务提醒': '/crm/hub/reminders',
  '库存管理/库存查询': '/inventory/hub/balances',
  '库存管理/仓管待入库': '/inventory/hub/inbound',
  '库存管理/地磅台账': '/inventory/hub/ledger',
  '库存管理/亏料预警': '/inventory/hub/shortage',
  '库存管理/过量预警': '/inventory/hub/excess',
  '库存管理/入库质检': '/inventory/hub/inbound-qc',
  '库存管理/仓库盘点': '/inventory/hub/stocktakes',
  '库存管理/车间盘点': '/inventory/hub/workshop-stocktakes',
  '库存管理/仓库盘点记录': '/inventory/hub/stocktake-records',
  '库存管理/销售退皮': '/inventory/hub/peels',
  '库存管理/物料调拨耗用': '/inventory/hub/transfers',
  '库存管理/商品调价组装拆分': '/inventory/hub/assemble',
  '库存管理/物料转应付': '/inventory/hub/to-payable',
  '库存管理/在途量统计': '/inventory/hub/in-transits',
  '库存管理/待用量统计': '/inventory/hub/reservations',
  '库存管理/可用量分析': '/inventory/hub/availability',
  '库存管理/期初入库': '/inventory/hub/openings',
  '库存管理/出入库记录汇总': '/inventory/hub/stock-txns',
  '库存管理/采购退货': '/inventory/hub/purchase-returns',
  '库存管理/箱码管理': '/inventory/hub/boxes',
  '产品管理/产品档案': '/product/hub/products',
  '产品管理/产品单位管理': '/product/hub/units',
  '产品管理/APP产品排序': '/product/hub/app-sorts',
  '产品管理/生产规格绑定': '/product/hub/specs',
  '固定资产管理/固定资产类别': '/asset/hub/categories',
  '固定资产管理/固定资产项目': '/asset/hub/fixed-assets',
  '固定资产管理/固定资产内部转移': '/asset/hub/transfers',
  '固定资产管理/固定资产统计': '/asset/hub/stats',
  '财务管理/账目管理': '/finance/hub/subjects',
  '财务管理/交易流水账': '/finance/hub/ledger',
  '财务管理/收入支出明细': '/finance/hub/income-expenses',
  '财务管理/订单管理': '/finance/hub/orders',
  '财务管理/小程序管理': '/finance/hub/miniprogram',
  '财务管理/凭证管理': '/finance/hub/vouchers',
  '财务管理/发票管理': '/finance/hub/invoices',
  '财务管理/收款核单': '/finance/hub/writeoffs',
  '财务管理/外币结汇': '/finance/hub/fx',
  '财务管理/结汇查询': '/finance/hub/fx-query',
  '财务管理/分摊撤销': '/finance/hub/allocations',
  '财务管理/收款预警': '/finance/hub/alerts',
  '财务管理/出纳对账': '/finance/hub/reconciles',
  '财务管理/预收预付管理': '/finance/hub/prepays',
  '财务管理/成本核算': '/finance/hub/cost-accountings',
  '财务管理/合同利润': '/finance/hub/contract-profits',
  '财务管理/销售认款': '/finance/hub/recognitions',
  '财务管理/销售退货退单': '/finance/hub/return-finances',
  '财务管理/往来调整单': '/finance/hub/arap',
  '财务管理/财务审批': '/finance/hub/approvals',
  '财务管理/资金管理': '/finance/hub/funds',
  '财务管理/财务报表': '/finance/hub/statements',
  '财务管理/成本明细溯源表': '/finance/hub/cost-traces',
  '财务管理/月度结转': '/finance/hub/month-closes',
  '统计报表/企业报表': '/report/hub/enterprise',
  '统计报表/老板驾驶舱': '/report/hub/boss',
  '统计报表/生产看板': '/report/hub/production-board',
  '统计报表/生产实况': '/report/hub/live',
  '统计报表/客户询价查询': '/report/hub/inquiries',
  '统计报表/CRM统计': '/report/hub/crm-stats',
  '统计报表/日统计报表': '/report/hub/daily',
  '统计报表/毛利润统计': '/report/hub/gross-profit',
  '统计报表/质检报表': '/report/hub/qc',
  '统计报表/账目统计': '/report/hub/accounts',
  '统计报表/出入库查询': '/report/hub/stock-txns',
  '统计报表/收发存明细': '/report/hub/stock-ledger',
  '统计报表/跟进记录查询': '/report/hub/follow-ups',
  '统计报表/销售重量统计': '/report/hub/sales-weight',
  '统计报表/产品销售查询': '/report/hub/product-sales',
  '统计报表/系统物流查询': '/report/hub/logistics',
  '统计报表/成本利润表': '/report/hub/cost-profit',
  '统计报表/资产负债表': '/report/hub/balance-sheet',
  '统计报表/现金流量表': '/report/hub/cash-flow',
  '统计报表/利润表': '/report/hub/income-statement',
  '审批管理/任务管理': '/approval/hub/tasks',
  '审批管理/单据审核': '/approval/hub/doc-reviews',
  '审批管理/费用财务审批': '/approval/hub/expense-finance',
  '审批管理/询价财务审批': '/approval/hub/inquiry-finance',
  '审批管理/询价明细审批': '/approval/hub/inquiry-lines',
  '审批管理/采购审批': '/approval/hub/purchases',
  '审批管理/采购计划单审批': '/approval/hub/purchase-plans',
  '审批管理/事务申请审批': '/approval/hub/affairs',
  '审批管理/费用申请': '/approval/hub/expense-requests',
  '审批管理/考勤审批': '/approval/hub/attendance',
  '生产管理/工序定义': '/production/hub/processes',
  '生产管理/工艺流程': '/production/hub/routings',
  '生产管理/产线班次': '/production/hub/shifts',
  '生产管理/例外派岗': '/production/hub/dispatches',
  '生产管理/灵活派发工单': '/production/hub/flex',
  '生产管理/过站记录': '/production/hub/reports',
  '生产管理/计件工资': '/production/hub/piecework',
  '生产管理/计件领料表': '/production/hub/piece-issue',
  '生产管理/自动BOM': '/production/hub/boms',
  '生产管理/MRP物料分析': '/production/hub/mrp',
  '生产管理/联动式领料': '/production/hub/requisitions',
  '生产管理/车间工作台': '/production/hub/workbench',
  '生产管理/工序在制': '/production/hub/process-wip',
  '生产管理/车间管理': '/production/hub/workshops',
  '生产管理/委外加工': '/production/hub/outsources',
  '生产管理/受托加工生产流程管控': '/production/hub/consignments',
  '生产管理/成本隐藏': '/production/hub/cost-hide',
  '生产管理/一单多商品': '/production/hub/multi-products',
  '生产管理/进度跟踪': '/production/hub/progress',
  '生产管理/质检管理': '/production/hub/qc',
  '生产管理/返修单': '/production/hub/reworks',
  '生产管理/废料管理': '/production/hub/scraps',
  '生产管理/退库未用完还仓': '/production/hub/process-returns',
  '生产管理/生产任务单': '/production/hub/tasks',
  '生产管理/多单整合管理': '/production/hub/merges',
  '生产管理/图纸分发': '/production/hub/drawings',
  // 兼容旧菜单名
  '生产管理/工序设置': '/production/hub/processes',
  '生产管理/工序管理': '/production/hub/processes',
  '生产管理/生产派工': '/production/hub/dispatches',
  '生产管理/扫码报工': '/production/hub/reports',
  '生产管理/加工记录': '/production/hub/reports',
  '人事管理/员工档案': '/hr/employees',
  '人事管理/部门管理': '/hr/departments',
  '人事管理/权限分配': '/hr/permissions',
  '人事管理/入职登记': '/hr/onboards',
  '人事管理/离职登记': '/hr/offboards',
  '人事管理/工具领还': '/hr/tool-issues',
  '人事管理/考勤管理': '/hr/attendance',
  '人事管理/班次管理': '/hr/shifts',
  '人事管理/绩效管理': '/hr/performance',
  '人事管理/请假管理': '/hr/leaves',
  '人事管理/考勤明细': '/hr/attendance-details',
  '人事管理/加班补卡统计': '/hr/overtime-stats',
  '人事管理/考勤月度统计': '/hr/attendance-monthly',
  '人事管理/考勤绩效汇总': '/hr/attendance-perf',
  '人事管理/外访明细': '/hr/field-visits',
  '人事管理/备忘录管理': '/hr/memos',
  '人事管理/员工日志': '/hr/journals',
  '工资管理/工人信息管理': '/payroll/workers',
  '工资管理/工资批量管理': '/payroll/batch',
  '工资管理/工序工资': '/payroll/wage-rates',
  '工资管理/薪酬核算': '/payroll/sheets',
  '工资管理/销售提成': '/payroll/commissions',
  '采购管理/供应商管理': '/purchase/hub/suppliers',
  '采购管理/农户档案': '/purchase/hub/farmers',
  '采购管理/过磅收货': '/purchase/hub/weigh',
  '采购管理/过磅流程编排': '/purchase/hub/flow-graphs',
  '采购管理/过磅品种': '/purchase/hub/varieties',
  '采购管理/溯源批号': '/purchase/hub/trace-batches',
  '采购管理/农户结算': '/purchase/hub/settlements',
  '采购管理/原料溯源': '/purchase/hub/trace',
  '采购管理/采购申请': '/purchase/hub/requests',
  '采购管理/采购计划单': '/purchase/hub/plans',
  '采购管理/采购入库': '/purchase/hub/inbounds',
  '采购管理/来料质检': '/purchase/hub/qcs',
  '采购管理/采购退货': '/purchase/hub/returns',
  '采购管理/采购分析': '/purchase/hub/analytics',
  '采购管理/历史价格查看': '/purchase/hub/prices',
  '采购管理/采购任务管理': '/purchase/hub/tasks',
  '系统管理/基础设置': '/system/settings',
  '系统管理/自定义打印': '/system/print-templates',
  '系统管理/自定义菜单': '/iam/menus',
  '系统管理/自定义权限': '/iam/permissions',
  '系统管理/表格自定义': '/system/table-customs',
  '系统管理/公式设置': '/system/formulas',
  '系统管理/销售设置': '/system/sales-settings',
  '系统管理/生产设置': '/system/production-settings',
  '系统管理/物流信息管理': '/system/logistics/carriers',
  '系统管理/审批流程设定': '/system/approval-flows',
  '系统管理/人事调动': '/system/personnel-transfers',
  '系统管理/登录控制': '/iam/login-policy',
  '系统管理/批量改价': '/system/batch-price-jobs',
  '系统管理/批量核算工资': '/system/batch-payroll-jobs',
  '系统管理/单据审批': '/system/doc-approve-switches',
  '系统管理/单据锁定': '/system/doc-lock-rules',
  '系统管理/单据通知': '/system/notify-rules',
  '系统管理/单据编辑': '/system/doc-edit-rules',
  '系统管理/单据删除': '/system/doc-delete-rules',
  '系统管理/事项提醒': '/system/reminders',
  '系统管理/多条件检索': '/system/search-configs',
  '系统管理/账户冻结': '/iam/users',
  '系统管理/财审管控': '/system/finance-audit-controls',
  '系统管理/学堂管理': '/system/courses',
  '系统管理/知识库': '/system/knowledge',
  '系统管理/图纸管理': '/system/drawings',
  '系统管理/文档管理': '/system/documents',
  '系统管理/员工日志': '/system/employee-journals',
  '系统管理/操作日志': '/automation/logs',
  '系统管理/数据修复': '/automation/repairs',
  '系统管理/业务闭环': '/loops',
  '系统管理/公告设置': '/system/announcements',
  '系统管理/备忘录': '/system/memos',
  '系统管理/工单中心': '/workflow/tickets',
}

export function adminSpecialPath(domain: string, module: string): string | undefined {
  return ADMIN_SPECIAL_MODULE_PATHS[`${domain}/${module}`]
}

/** 当前路由是否对应该菜单项（含专用页） */
export function isAdminModuleActive(
  domain: string,
  module: string,
  routePath: string,
  routeDomain?: string,
  routeModule?: string,
): boolean {
  const special = adminSpecialPath(domain, module)
  if (special) {
    if (special === '/') return routePath === '/' || routePath === ''
    return routePath === special || routePath.startsWith(special + '/')
  }
  return routeDomain === domain && routeModule === module
}

/** path → { domain, module } 反查；同前缀时优先最长精确匹配 */
export function adminModuleForPath(path: string): { domain: string; module: string } | null {
  let best: { domain: string; module: string; len: number } | null = null
  for (const [key, p] of Object.entries(ADMIN_SPECIAL_MODULE_PATHS)) {
    if (path === p || path.startsWith(p + '/')) {
      if (!best || p.length > best.len) {
        const [domain, module] = key.split('/')
        best = { domain, module, len: p.length }
      }
    }
  }
  return best ? { domain: best.domain, module: best.module } : null
}
