package apigen

import "github.com/gin-gonic/gin"

// RegisterProductionExtra mounts production delivery actions beyond OpenAPI gen.
func RegisterProductionExtra(r *gin.RouterGroup, h Handler) {
	r.POST("/production/consignments/:id/progress", h.Dispatch("POST", "/api/v1/production/consignments/{id}/progress", "/production/consignments/:id/progress", "production/consignments", "action:progress"))
	r.POST("/production/cost-hide-policies", h.Dispatch("POST", "/api/v1/production/cost-hide-policies", "/production/cost-hide-policies", "production/cost-hide-policies", "create"))
	r.GET("/production/drawing-links/:id", h.Dispatch("GET", "/api/v1/production/drawing-links/{id}", "/production/drawing-links/:id", "production/drawing-links", "get"))
	r.GET("/production/shifts", h.Dispatch("GET", "/api/v1/production/shifts", "/production/shifts", "production/shifts", "list"))
	r.POST("/production/shifts", h.Dispatch("POST", "/api/v1/production/shifts", "/production/shifts", "production/shifts", "create"))
	r.GET("/production/shifts/:id", h.Dispatch("GET", "/api/v1/production/shifts/{id}", "/production/shifts/:id", "production/shifts", "get"))
	r.PUT("/production/shifts/:id", h.Dispatch("PUT", "/api/v1/production/shifts/{id}", "/production/shifts/:id", "production/shifts", "update"))
	r.POST("/production/shifts/:id/close", h.Dispatch("POST", "/api/v1/production/shifts/{id}/close", "/production/shifts/:id/close", "production/shifts", "action:close"))
	r.POST("/production/shifts/:id/members", h.Dispatch("POST", "/api/v1/production/shifts/{id}/members", "/production/shifts/:id/members", "production/shifts", "action:add-member"))
	r.DELETE("/production/shifts/:id/members/:memberId", h.Dispatch("DELETE", "/api/v1/production/shifts/{id}/members/{memberId}", "/production/shifts/:id/members/:memberId", "production/shifts", "action:remove-member"))
	r.PUT("/production/flow-rules", h.Dispatch("PUT", "/api/v1/production/flow-rules", "/production/flow-rules", "production/flow-rules", "update"))

	r.GET("/production/process-returns", h.Dispatch("GET", "/api/v1/production/process-returns", "/production/process-returns", "production/process-returns", "list"))
	r.POST("/production/process-returns", h.Dispatch("POST", "/api/v1/production/process-returns", "/production/process-returns", "production/process-returns", "create"))
	r.GET("/production/process-returns/:id", h.Dispatch("GET", "/api/v1/production/process-returns/{id}", "/production/process-returns/:id", "production/process-returns", "get"))
	r.POST("/production/process-returns/:id/submit", h.Dispatch("POST", "/api/v1/production/process-returns/{id}/submit", "/production/process-returns/:id/submit", "production/process-returns", "action:submit"))
	r.POST("/production/process-returns/:id/approve", h.Dispatch("POST", "/api/v1/production/process-returns/{id}/approve", "/production/process-returns/:id/approve", "production/process-returns", "action:approve"))
	r.POST("/production/process-returns/:id/reject", h.Dispatch("POST", "/api/v1/production/process-returns/{id}/reject", "/production/process-returns/:id/reject", "production/process-returns", "action:reject"))
	r.POST("/production/process-returns/:id/transfer", h.Dispatch("POST", "/api/v1/production/process-returns/{id}/transfer", "/production/process-returns/:id/transfer", "production/process-returns", "action:transfer"))
	r.POST("/production/process-returns/:id/warehouse-confirm", h.Dispatch("POST", "/api/v1/production/process-returns/{id}/warehouse-confirm", "/production/process-returns/:id/warehouse-confirm", "production/process-returns", "action:warehouse-confirm"))
	r.POST("/production/report-works/:id/void", h.Dispatch("POST", "/api/v1/production/report-works/{id}/void", "/production/report-works/:id/void", "production/report-works", "action:void"))
	r.POST("/production/board-issues", h.Dispatch("POST", "/api/v1/production/board-issues", "/production/board-issues", "production/board-issues", "create"))
	r.POST("/production/board-issues/return", h.Dispatch("POST", "/api/v1/production/board-issues/return", "/production/board-issues/return", "production/board-issues", "action:return"))
	r.POST("/production/board-moves", h.Dispatch("POST", "/api/v1/production/board-moves", "/production/board-moves", "production/board-moves", "create"))
	r.GET("/production/trace-productions", h.Dispatch("GET", "/api/v1/production/trace-productions", "/production/trace-productions", "production/trace-productions", "list"))
	r.GET("/production/trace-productions/logs", h.Dispatch("GET", "/api/v1/production/trace-productions/logs", "/production/trace-productions/logs", "production/trace-productions", "list"))
	r.GET("/production/trace-productions/:code/wip", h.Dispatch("GET", "/api/v1/production/trace-productions/{code}/wip", "/production/trace-productions/:code/wip", "production/trace-productions", "get"))
	r.GET("/production/trace-productions/:code/routing-options", h.Dispatch("GET", "/api/v1/production/trace-productions/{code}/routing-options", "/production/trace-productions/:code/routing-options", "production/trace-productions", "get"))
	r.GET("/production/trace-productions/:code/report", h.Dispatch("GET", "/api/v1/production/trace-productions/{code}/report", "/production/trace-productions/:code/report", "production/trace-productions", "get"))
	r.GET("/production/trace-productions/:code/material-locations", h.Dispatch("GET", "/api/v1/production/trace-productions/{code}/material-locations", "/production/trace-productions/:code/material-locations", "production/trace-productions", "get"))
	r.POST("/production/trace-productions/start", h.Dispatch("POST", "/api/v1/production/trace-productions/start", "/production/trace-productions/start", "production/trace-productions", "action:start"))
	r.POST("/production/trace-productions/complete", h.Dispatch("POST", "/api/v1/production/trace-productions/complete", "/production/trace-productions/complete", "production/trace-productions", "action:complete"))
	r.POST("/production/trace-productions/process-complete", h.Dispatch("POST", "/api/v1/production/trace-productions/process-complete", "/production/trace-productions/process-complete", "production/trace-productions", "action:process-complete"))
	r.POST("/production/trace-productions/process-start", h.Dispatch("POST", "/api/v1/production/trace-productions/process-start", "/production/trace-productions/process-start", "production/trace-productions", "action:process-start"))
	r.POST("/production/trace-productions/process-stop", h.Dispatch("POST", "/api/v1/production/trace-productions/process-stop", "/production/trace-productions/process-stop", "production/trace-productions", "action:process-stop"))
	r.GET("/production/process-issues", h.Dispatch("GET", "/api/v1/production/process-issues", "/production/process-issues", "production/process-issues", "list"))
	r.GET("/production/process-issues/:id", h.Dispatch("GET", "/api/v1/production/process-issues/{id}", "/production/process-issues/:id", "production/process-issues", "get"))
	r.POST("/production/process-issues/:id/return-apply", h.Dispatch("POST", "/api/v1/production/process-issues/{id}/return-apply", "/production/process-issues/:id/return-apply", "production/process-issues", "action:return-apply"))
	r.POST("/production/process-issues/:id/return-approve", h.Dispatch("POST", "/api/v1/production/process-issues/{id}/return-approve", "/production/process-issues/:id/return-approve", "production/process-issues", "action:return-approve"))
	r.POST("/production/process-issues/:id/return-reject", h.Dispatch("POST", "/api/v1/production/process-issues/{id}/return-reject", "/production/process-issues/:id/return-reject", "production/process-issues", "action:return-reject"))
	r.POST("/production/process-issues/:id/issue-approve", h.Dispatch("POST", "/api/v1/production/process-issues/{id}/issue-approve", "/production/process-issues/:id/issue-approve", "production/process-issues", "action:issue-approve"))
	r.POST("/production/process-issues/:id/issue-reject", h.Dispatch("POST", "/api/v1/production/process-issues/{id}/issue-reject", "/production/process-issues/:id/issue-reject", "production/process-issues", "action:issue-reject"))
	r.POST("/production/process-issues/:id/confirm-done", h.Dispatch("POST", "/api/v1/production/process-issues/{id}/confirm-done", "/production/process-issues/:id/confirm-done", "production/process-issues", "action:confirm-done"))
	r.GET("/production/process-stock-ins", h.Dispatch("GET", "/api/v1/production/process-stock-ins", "/production/process-stock-ins", "production/process-stock-ins", "list"))
	r.POST("/production/process-stock-ins", h.Dispatch("POST", "/api/v1/production/process-stock-ins", "/production/process-stock-ins", "production/process-stock-ins", "create"))
	r.GET("/production/process-stock-ins/:id", h.Dispatch("GET", "/api/v1/production/process-stock-ins/{id}", "/production/process-stock-ins/:id", "production/process-stock-ins", "get"))
	r.POST("/production/process-stock-ins/:id/approve", h.Dispatch("POST", "/api/v1/production/process-stock-ins/{id}/approve", "/production/process-stock-ins/:id/approve", "production/process-stock-ins", "action:approve"))
	r.POST("/production/process-stock-ins/:id/reject", h.Dispatch("POST", "/api/v1/production/process-stock-ins/{id}/reject", "/production/process-stock-ins/:id/reject", "production/process-stock-ins", "action:reject"))
	r.POST("/production/board-close/preview", h.Dispatch("POST", "/api/v1/production/board-close/preview", "/production/board-close/preview", "production/board-close", "action:preview"))
	r.POST("/production/board-close", h.Dispatch("POST", "/api/v1/production/board-close", "/production/board-close", "production/board-close", "create"))
	r.GET("/production/process-wip", h.Dispatch("GET", "/api/v1/production/process-wip", "/production/process-wip", "production/process-wip", "list"))
	r.GET("/production/process-wip/boxes", h.Dispatch("GET", "/api/v1/production/process-wip/boxes", "/production/process-wip/boxes", "production/process-wip", "list"))
	r.GET("/production/process-yields", h.Dispatch("GET", "/api/v1/production/process-yields", "/production/process-yields", "production/process-yields", "list"))
	r.GET("/production/process-yields/traces", h.Dispatch("GET", "/api/v1/production/process-yields/traces", "/production/process-yields/traces", "production/process-yields", "list"))
	r.POST("/production/piecework-summaries/day-settle", h.Dispatch("POST", "/api/v1/production/piecework-summaries/day-settle", "/production/piecework-summaries/day-settle", "production/piecework-summaries", "action:day-settle"))
	r.GET("/production/station-flow-logs", h.Dispatch("GET", "/api/v1/production/station-flow-logs", "/production/station-flow-logs", "production/station-flow-logs", "list"))
}
