package openapi

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EmitRoutesGo writes internal/apigen/routes_gen.go, scripts/openapi_ops.json,
// and a predicted scripts/gin_routes.json (erp-api startup may overwrite with live dump).
func EmitRoutesGo(root string, ops []Op) (emitted int, err error) {
	outGo := filepath.Join(root, "internal", "apigen", "routes_gen.go")
	outJSON := filepath.Join(root, "scripts", "openapi_ops.json")
	outGin := filepath.Join(root, "scripts", "gin_routes.json")

	type row struct {
		Method string `json:"method"`
		Path   string `json:"path"`
	}
	rows := make([]row, 0, len(ops))
	ginRows := make([]row, 0, len(ops))
	for _, o := range ops {
		rows = append(rows, row{Method: o.Method, Path: o.Path})
		gp := GinPath(o.Path)
		ginRows = append(ginRows, row{Method: o.Method, Path: "/api/v1" + gp})
	}
	jb, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		return 0, err
	}
	if err := os.MkdirAll(filepath.Dir(outJSON), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(outJSON, jb, 0o644); err != nil {
		return 0, err
	}
	gb, err := json.MarshalIndent(ginRows, "", "  ")
	if err != nil {
		return 0, err
	}
	if err := os.WriteFile(outGin, gb, 0o644); err != nil {
		return 0, err
	}

	var b strings.Builder
	b.WriteString("// Code generated by go run ./cmd/erp-tools gen-routes; DO NOT EDIT.\n")
	b.WriteString("package apigen\n\n")
	b.WriteString("import \"github.com/gin-gonic/gin\"\n\n")
	b.WriteString("// RegisterGenerated mounts all OpenAPI paths onto /api/v1 group.\n")
	b.WriteString("func RegisterGenerated(r *gin.RouterGroup, h Handler) {\n")

	seen := map[string]struct{}{}
	for _, o := range ops {
		if strings.HasPrefix(o.Path, "/api/v1/health") ||
			strings.HasPrefix(o.Path, "/api/v1/auth/") ||
			strings.HasPrefix(o.Path, "/api/v1/mqtt/") {
			continue
		}
		gp := GinPath(o.Path)
		key := o.Method + "\t" + gp
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		action := Classify(o.Method, o.Path)
		rkey := ResourceKey(o.Path)
		fmt.Fprintf(&b, "\tr.%s(%q, h.Dispatch(%q, %q, %q, %q, %q))\n",
			o.Method, gp, o.Method, o.Path, gp, rkey, action)
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(outGo), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(outGo, []byte(b.String()), 0o644); err != nil {
		return 0, err
	}
	return len(seen), nil
}

// GenRoutes reads OpenAPI and emits routes.
func GenRoutes(root string) (opsCount, emitted int, err error) {
	openapiPath := filepath.Join(root, "docs", "openapi3.0-加工厂ERP.yaml")
	raw, err := os.ReadFile(openapiPath)
	if err != nil {
		return 0, 0, err
	}
	ops := ParseOps(string(raw))
	n, err := EmitRoutesGo(root, ops)
	return len(ops), n, err
}
