# -*- coding: utf-8 -*-
"""Parse OpenAPI and emit Go route registration + coverage report."""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "docs" / "openapi3.0-加工厂ERP.yaml"
OUT_GO = ROOT / "internal" / "apigen" / "routes_gen.go"
OUT_JSON = ROOT / "scripts" / "openapi_ops.json"


def parse_ops(text: str):
    body = text.split("paths:", 1)[1].split("components:", 1)[0]
    ops = []
    cur = None
    for line in body.splitlines():
        if line.startswith("  /"):
            cur = line.strip().rstrip(":")
            continue
        m = re.match(r"    (get|post|put|patch|delete):\s*$", line)
        if m and cur:
            ops.append((m.group(1).upper(), cur))
    return ops


def gin_path(openapi_path: str) -> str:
    # /api/v1/foo/{id}/bar -> /foo/:id/bar (relative to /api/v1 group)
    p = openapi_path
    if p.startswith("/api/v1"):
        p = p[len("/api/v1") :]
    return re.sub(r"\{([^}]+)\}", r":\1", p)


def resource_key(path: str) -> str:
    """Normalize path to resource key for erp_doc storage."""
    p = path
    if p.startswith("/api/v1/"):
        p = p[len("/api/v1/") :]
    # strip trailing param segments for collection key
    parts = []
    for seg in p.split("/"):
        if seg.startswith("{") or seg.startswith(":"):
            break
        parts.append(seg)
    return "/".join(parts) if parts else p


def classify(method: str, path: str):
    """Return action name for engine dispatch."""
    segs = path.rstrip("/").split("/")
    last = segs[-1] if segs else ""
    if last.startswith("{") or last.startswith(":"):
        if method == "GET":
            return "get"
        if method == "PUT" or method == "PATCH":
            return "update"
        if method == "DELETE":
            return "delete"
        return "action"
    # collection or collection action
    if method == "GET":
        return "list"
    if method == "POST":
        # if previous is {id}, it's item action: /x/{id}/post
        if len(segs) >= 2 and (segs[-2].startswith("{") or segs[-2].startswith(":")):
            return "action:" + last
        return "create"
    if method == "PUT":
        return "replace"
    if method == "DELETE":
        return "delete_collection"
    return "action"


def emit_go(ops):
    lines = [
        "// Code generated by scripts/gen_routes.py; DO NOT EDIT.",
        "package apigen",
        "",
        'import "github.com/gin-gonic/gin"',
        "",
        "// RegisterGenerated mounts all OpenAPI paths onto /api/v1 group.",
        "func RegisterGenerated(r *gin.RouterGroup, h Handler) {",
    ]
    # dedupe exact method+ginpath; skip health/auth/mqtt (registered by dedicated packages)
    seen = set()
    for method, opath in ops:
        if (
            opath.startswith("/api/v1/health")
            or opath.startswith("/api/v1/auth/")
            or opath.startswith("/api/v1/mqtt/")
        ):
            continue
        gp = gin_path(opath)
        key = (method, gp)
        if key in seen:
            continue
        seen.add(key)
        action = classify(method, opath)
        rkey = resource_key(opath)
        gin_method = {"GET": "GET", "POST": "POST", "PUT": "PUT", "PATCH": "PATCH", "DELETE": "DELETE"}[method]
        lines.append(
            f'\tr.{gin_method}("{gp}", h.Dispatch({json.dumps(method)}, {json.dumps(opath)}, {json.dumps(gp)}, {json.dumps(rkey)}, {json.dumps(action)}))'
        )
    lines.append("}")
    lines.append("")
    OUT_GO.parent.mkdir(parents=True, exist_ok=True)
    OUT_GO.write_text("\n".join(lines), encoding="utf-8")
    return len(seen)


def main():
    text = OPENAPI.read_text(encoding="utf-8")
    ops = parse_ops(text)
    OUT_JSON.write_text(json.dumps([{"method": m, "path": p} for m, p in ops], ensure_ascii=False, indent=2), encoding="utf-8")
    n = emit_go(ops)
    print(f"ops={len(ops)} routes_emitted={n} -> {OUT_GO}")


if __name__ == "__main__":
    main()
